package com.alarysai.alarysai.di

import android.content.Context
import com.alarysai.alarysai.R
import com.alarysai.alarysai.feature.auth.di.GoogleSignInConfig
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent

@Module
@InstallIn(SingletonComponent::class)
object GoogleSignInModule {

    /** `default_web_client_id` is generated by the google-services plugin from `google-services.json`. */
    @Provides
    fun providesGoogleSignInConfig(@ApplicationContext context: Context) =
        GoogleSignInConfig(webClientId = context.getString(R.string.default_web_client_id))
}
